### ISSUE TITLE
There is no way to change the API to use production URL

### ISSUE THREAD

**Issue by Shannon-Abco** [GBSEcom/DotNet#1]
public static Gateway Create(MerchantCredentials _credentials) 

needs to be changed to accept a production url https://prod.api.firstdata.com/gateway/v2/payments

**Comment by ericmargules** [comment]
Thanks for reaching out, @Shannon-Abco. We've updated the SDK to allow you to pass your own prod URL or simply mark the option production parameter as true:

            // For use in production, supply true as the optional production argument:

            Gateway gateway = Gateway.create(credentials, true);

            // Or supply the production URL directly:

            string productionURL = "https://prod.api.firstdata.com/gateway/v2";

            Gateway gateway = Gateway.create(credentials, productionURL);

**Comment by ericmargules** [comment]
Hi @Shannon-Abco , let me know if this solves your problem. If I don't hear from you by EOD Monday, I'll go ahead and close it.
