### ISSUE TITLE
UsePaymentToken should allow a null CardFunction parameter

### ISSUE THREAD

**Issue by kellywahl** [GBSEcom/DotNet#4]
During the creation of a payload object **PaymentTokenSaleTransaction**, one of the sub object UsePaymentToken has a parameter called **function** which takes a CardFunction object. The Fiserv gateway expects this parameter to not be set or included which means it should be null in the payload.  Unfortunately the constructor sets this value to 0 as a default if you pass it in. The following code illustrates this.

var transactionPayload = new PaymentTokenSaleTransaction(
               requestType: "PaymentTokenSaleTransaction",
               transactionAmount: new Amount(
                   total: 200,
                   currency: "GBP"),
               transactionOrigin: TransactionOrigin.ECOM,
               paymentMethod: new PaymentTokenPaymentMethod(
                   new UsePaymentToken(
                       value: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                       tokenOriginStoreId: "1234567890"
                   )
               ),
               merchantTransactionId: "12345678",
               storeId: "1234567890");

{"paymentMethod":{"paymentToken":{**"function":0**,"value":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","tokenOriginStoreId":"1234567890"}},"transactionOrigin":"ECOM","requestType":"PaymentTokenSaleTransaction","transactionAmount":{"total":200.0,"currency":"GBP"},"storeId":"1234567890","merchantTransactionId":"12345678"}

The workaround is the initialise the UsePaymentToken object then set the Function property to null.

var paymentToken = new UsePaymentToken(
                value: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                tokenOriginStoreId: "1234567890"
            );
            paymentToken.Function = null;
            var transactionPayload = new PaymentTokenSaleTransaction(
               requestType: "PaymentTokenSaleTransaction",
               transactionAmount: new Amount(
                   total: 200,
                   currency: "GBP"),
               transactionOrigin: TransactionOrigin.ECOM,
               paymentMethod: new PaymentTokenPaymentMethod(
                   paymentToken
               ),
               merchantTransactionId: "12345678",
               storeId: "1234567890");

**Comment by ericmargules** [comment]
Hey @kellywahl, 
Thanks for reporting this issue. I'm unable to recreate the issue by building the model as you have. Here is the code snippet taken from your above comment: 

                var transactionPayload = new PaymentTokenSaleTransaction(
                    requestType: "PaymentTokenSaleTransaction",
                    transactionAmount: new Amount(
                        total: 200,
                        currency: "GBP"
                    ),
                    transactionOrigin: TransactionOrigin.ECOM,
                    paymentMethod: new PaymentTokenPaymentMethod(
                        new UsePaymentToken(
                            value: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                            tokenOriginStoreId: "1234567890"
                        )
                    ),
                    merchantTransactionId: "12345678",
                    storeId: "1234567890"
                );
                Console.WriteLine(transactionPayload.ToJson());


And the output: 

{
  "paymentMethod": {
    "paymentToken": {
      "value": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "tokenOriginStoreId": "1234567890"
    }
  },
  "transactionOrigin": "ECOM",
  "requestType": "PaymentTokenSaleTransaction",
  "transactionAmount": {
    "total": 200.0,
    "currency": "GBP"
  },
  "storeId": "1234567890",
  "merchantTransactionId": "12345678"
}

As you can see, cardFunction is not set in this instance. Can you provide some more feedback about how you're outputting that object (`{"paymentMethod":{"paymentToken":{"function":0,"value":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","tokenOriginStoreId":"1234567890"}},"transactionOrigin":"ECOM","requestType":"PaymentTokenSaleTransaction","transactionAmount":{"total":200.0,"currency":"GBP"},"storeId":"1234567890","merchantTransactionId":"12345678"}`)

Thanks again

**Comment by kellywahl** [comment]
Hi @ericmargules ,

We are using the exact same method as you. Is it possible our SDK is out of date?

Here is the signature of the constructor for **UsePaymentToken**

```c#
public UsePaymentToken(
      string value = null,
      string tokenOriginStoreId = null,
      CardFunction function = (CardFunction) 0,
      string securityCode = null,
      Expiration expiryDate = null)
    {
      if (value == null)
        throw new InvalidDataException("value is a required property for UsePaymentToken and cannot be null");
      this.Value = value;
      this.TokenOriginStoreId = tokenOriginStoreId;
      this.Function = new CardFunction?(function);
      this.SecurityCode = securityCode;
      this.ExpiryDate = expiryDate;
    }
```
You can see that if you don't supply the parameter "function", it will be set to 0 hence creating **function:0** in the payload. The enum CardFunction is not nullable so I'm not sure how you are getting your payload.

We are using the Nuget package FirstData.Gateway 1.7.0

**Comment by ericmargules** [comment]
@kellywahl I think I've found the source of the issue you're experiencing. We're working on an update to fix it. For now the workaround you suggested should suffice. I'll update this issue once it's resolved.

**Comment by kellywahl** [comment]
@ericmargules  - any update on this?

**Comment by ericmargules** [comment]
@kellywahl would you update to 1.8.0 and tell me if the issue persists? I think it's been resolved.

**Comment by FuzzyBearBTC** [comment]
Just to confirm that updating to the latest version on FirstData has resolved the issue
