### ISSUE TITLE
SubmitPrimaryTransaction method is not working on https://cert.api.firstdata.com/gateway/v2/payments

### ISSUE THREAD

**Issue by tushar-thaker** [GBSEcom/DotNet#7]
When we use https://cert.api.firstdata.com/gateway/v2/payments this URL Its not working. It throws an exception of a bad request.

Can you please give the name of the method which update methodNotificationStatus?

It really helps me.

**Comment by ericmargules** [comment]
Can you provide more information @tushar-thaker? That URL is the default sandbox URL and it does work for all endpoints.
