### ISSUE TITLE
SubmitPrimaryTransaction not working (PaymentCardSaleTransaction)

### ISSUE THREAD

**Issue by acomp123** [GBSEcom/DotNet#8]
Can anyone help in this?

I am working on IPG API and downloaded the C# SDK from the link https://github.com/GBSEcom/DotNet
there is an issue while testing "SubmitPrimaryTransaction" with the request type "PaymentCardSaleTransaction". issue is as follows,
Error message: "Data at root level is invalid. Line 2, position 13".
![image](https://user-images.githubusercontent.com/84851945/119663942-797f9e80-be50-11eb-8d24-a124d3897ab5.png)

below is the code for JSON request I am sending, (referred the section "Getting Started" at link https://github.com/GBSEcom/DotNet)

            string apiKey = "mayapikey";
            string apiSecret = "mayapisecret";
            MerchantCredentials credentials = new MerchantCredentials(apiKey, apiSecret);
            Gateway gateway = Gateway.Create(credentials);

            // For use in production, supply true as the optional production argument:
            // Gateway gateway = Gateway.create(credentials, true);
            // Or supply the production URL directly:
            // string productionURL = "https://prod.api.firstdata.com/gateway/v2";
            // Gateway gateway = Gateway.create(credentials, productionURL);

            string json_payload = @"{
                ""requestType"": ""PaymentCardSaleTransaction"",
                ""transactionAmount"": {
                    ""total"": 12.04,
                    ""currency"": ""USD""
                },
                ""paymentMethod"": {
                    ""paymentCard"": {
                    ""number"": ""5424180279791732"",
                    ""securityCode"": 123,
                    ""expiryDate"": {
                        ""month"": 12,
                        ""year"": 24
                        }
                    }
                }
            }";

            PaymentCardSaleTransaction payload = JsonConvert.DeserializeObject<PaymentCardSaleTransaction>(json_payload);

            try
            {
                payload.StoreId = "mystoreid";
                payload.TransactionOrigin = TransactionOrigin.ECOM;
                TransactionResponse response = gateway.SubmitPrimaryTransaction(payload);
                Console.WriteLine(response.ToJson());

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

**Comment by acomp123** [comment]
Can anyone help in as issue mentioned in previous post here. This is for IPG API code and C#.Net SDK downloaded from https://github.com/GBSEcom/DotNet on 26th May 2021. Do we need to do any changes in this code after downloading it to get the successful response (JSON requests). Sample JSON code for request is mentioned in above post.

**Comment by ericmargules** [comment]
@acomp123 you shouldn't require any changes to the sample code provided in the getting started section other than providing your credentials. This is not an error I've encountered before. Could be something to do with your environment.  I'd reach out to Integrations Support if you need help setting up the SDK

**Comment by acomp123** [comment]
Hi Eric, 
Thank you for your reply. We are doing a dry run through the source code that we downloaded from https://docs.firstdata.com/org/gateway/docs/api#sdks  for C#.Net. We have not integrated this to our source code yet.
Below are the request response details when we tried to test the same. 
The **store id** (removed while pasting here), **apiKey** and **apiSecret** we are using here is working fine for IPG V1 in our code but gives response as Unauthenticated for API version V2 as mentioned below. Message signature is also generated correctly (please refer all screenshots here).
**Can we get any help from integration support team in this?** **Is it like we need different store Ids for V2 than we are using for V1? Please guide.**

**Request JSON**
{
   "paymentMethod": {
      "paymentCard": {
         "number": "4111111111111111",
         "expiryDate": {
            "month": "12",
            "year": "24"
         },
         "securityCode": "123"
      }
   },
   "transactionOrigin": "ECOM",
   "requestType": "PaymentCardSaleTransaction",
   "transactionAmount": {
      "total": 12.04,
      "currency": "USD"
   },
   "storeId": "_ourstoreid_"
}

**Response JSON**
{
   "clientRequestId": "33a803ea-6536-47ce-80aa-46744eda55e1",
   "responseType": "Unauthenticated",
   "error": {
      "code": "401",
      "message": "Message Signature validation error"
   }
}

**Request Headers:** 
![image](https://user-images.githubusercontent.com/84851945/129014202-54aef458-3b84-4817-8062-a46b68d0b03e.png)

**Response status code shows: Unauthorized** 
![image](https://user-images.githubusercontent.com/84851945/129014273-03efb5b1-248d-4d13-8940-c56105162fc7.png)

**Request hitting at URL**: https://cert.api.firstdata.com/gateway/v2 as mentioned in below screenshot.
![image](https://user-images.githubusercontent.com/84851945/129014335-d4f4d6f5-256e-4d38-90a6-32c126bb7fec.png)

**Message signature logic in C#**
![image](https://user-images.githubusercontent.com/84851945/129014378-3c81742e-d608-46a6-a599-180cb6b45c28.png)

**Comment by ericmargules** [comment]
Please reach out to Integrations Support for help getting set up here. If they can't identify your issue, we can reopen this. Your message signature validation error usually arises when the payload you're passing in doesn't match what the library hashes and sends to the API.
